--------------------------------------------------------
--  File created - Monday-February-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_INFO
--------------------------------------------------------

  CREATE TABLE "SWAP"."ADMIN_INFO" 
   (	"PAN_CARD" VARCHAR2(20 BYTE), 
	"PHN_NUMBER1" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"COMPANY_NAME" VARCHAR2(20 BYTE), 
	"PHN_NUMBER2" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BILLING_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "SWAP"."BILLING_TRANSACTION" 
   (	"BILL_NUMBER" VARCHAR2(20 BYTE), 
	"PAN_NUMBER" VARCHAR2(20 BYTE), 
	"PHN_NUMBER" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TO_CUSTOMER" VARCHAR2(20 BYTE), 
	"BILL_DATE" DATE, 
	"DATE_OF_TRAVEL" DATE, 
	"DATE_OF_RETURN" DATE, 
	"TYPE_OF_VEHICLE" VARCHAR2(20 BYTE), 
	"VEHICLE_NUMBER" VARCHAR2(20 BYTE), 
	"VENDOR_CODE" VARCHAR2(20 BYTE), 
	"EMPLOYEE_NAME" VARCHAR2(20 BYTE), 
	"PACKAGE" VARCHAR2(20 BYTE), 
	"DUTY_TYPE" VARCHAR2(20 BYTE), 
	"EXTRA_KM" VARCHAR2(20 BYTE), 
	"EXTRA_TIME" VARCHAR2(20 BYTE), 
	"TOLL_CHARGE" VARCHAR2(20 BYTE), 
	"NIGHT_HALT" VARCHAR2(20 BYTE), 
	"STARTING_KM" VARCHAR2(20 BYTE), 
	"CLOSING_KM" VARCHAR2(20 BYTE), 
	"STARTING_TIME" VARCHAR2(20 BYTE), 
	"CLOSING_TIME" VARCHAR2(20 BYTE), 
	"TOTAL_KM" VARCHAR2(20 BYTE), 
	"AC_NOAC" VARCHAR2(20 BYTE), 
	"PKG_ALL0W_KM" VARCHAR2(20 BYTE), 
	"PKG_ALLOW_RATE" VARCHAR2(20 BYTE), 
	"EXTRA_KM_RATE" VARCHAR2(20 BYTE), 
	"PKG_AMOUNT" VARCHAR2(20 BYTE), 
	"EXTRA_AMOUNT" VARCHAR2(20 BYTE), 
	"TOTAL_AMOUNT" VARCHAR2(20 BYTE), 
	"SERVICE_TAX" VARCHAR2(20 BYTE), 
	"GRAND_TOTAL" VARCHAR2(20 BYTE), 
	"RS_IN_WORDS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "SWAP"."CUSTOMERS" 
   (	"CUSTOMER_NAME" VARCHAR2(20 BYTE), 
	"VENDOR_CODE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"EMPLOYEE_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RATES
--------------------------------------------------------

  CREATE TABLE "SWAP"."RATES" 
   (	"CUSTOMER" VARCHAR2(20 BYTE), 
	"DUTY_TYPE" VARCHAR2(20 BYTE), 
	"VEHICLE_TYPE" VARCHAR2(20 BYTE), 
	"PKG_RATE" VARCHAR2(20 BYTE), 
	"EXTRA_RATE" VARCHAR2(20 BYTE), 
	"VENDOR_CODE" VARCHAR2(20 BYTE), 
	"AC_NOAC" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SFAMILY
--------------------------------------------------------

  CREATE TABLE "SWAP"."SFAMILY" 
   (	"FAMILY_ID" NUMBER, 
	"FAMILY_HEAD" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SMEMBER
--------------------------------------------------------

  CREATE TABLE "SWAP"."SMEMBER" 
   (	"MEMBER_ID" NUMBER, 
	"FAMILY_ID" NUMBER, 
	"M_NAME_E" VARCHAR2(100 BYTE), 
	"M_NAME_M" VARCHAR2(100 BYTE), 
	"FAMILY_HEAD_STATUS" VARCHAR2(10 BYTE), 
	"M_SEX" VARCHAR2(10 BYTE), 
	"M_STATE" VARCHAR2(50 BYTE), 
	"M_DIST" VARCHAR2(50 BYTE), 
	"M_TAL" VARCHAR2(200 BYTE), 
	"M_GAON" VARCHAR2(200 BYTE), 
	"M_DOB" VARCHAR2(200 BYTE), 
	"M_WARD" NUMBER(*,0), 
	"M_CONTACT" VARCHAR2(11 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SSMSCONTACTS
--------------------------------------------------------

  CREATE TABLE "SWAP"."SSMSCONTACTS" 
   (	"S_NAME" VARCHAR2(200 BYTE), 
	"S_NUMBER" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SWAP.ADMIN_INFO
SET DEFINE OFF;
Insert into SWAP.ADMIN_INFO (PAN_CARD,PHN_NUMBER1,EMAIL,ADDRESS,COMPANY_NAME,PHN_NUMBER2) values ('AKHPN95056','9623121570','abc@gmail.com','S NO 74 | 7 RAJNIGANDHA HOUSING SOCIETY  , WALHEKAEWADI , CHINCHWAD , PUNE  411033','SAIKRUPA tRANSPORT','9881997456');
REM INSERTING into SWAP.BILLING_TRANSACTION
SET DEFINE OFF;
REM INSERTING into SWAP.CUSTOMERS
SET DEFINE OFF;
REM INSERTING into SWAP.RATES
SET DEFINE OFF;
REM INSERTING into SWAP.SFAMILY
SET DEFINE OFF;
Insert into SWAP.SFAMILY (FAMILY_ID,FAMILY_HEAD) values (2,'shreekant');
Insert into SWAP.SFAMILY (FAMILY_ID,FAMILY_HEAD) values (1,'swapnil');
REM INSERTING into SWAP.SMEMBER
SET DEFINE OFF;
Insert into SWAP.SMEMBER (MEMBER_ID,FAMILY_ID,M_NAME_E,M_NAME_M,FAMILY_HEAD_STATUS,M_SEX,M_STATE,M_DIST,M_TAL,M_GAON,M_DOB,M_WARD,M_CONTACT) values (1,2,'shreekant','shreekant','Yes','Male','Maharashtra','Ahmednagar','rahata','wakadi','23/02/91',2,'7083182041');
Insert into SWAP.SMEMBER (MEMBER_ID,FAMILY_ID,M_NAME_E,M_NAME_M,FAMILY_HEAD_STATUS,M_SEX,M_STATE,M_DIST,M_TAL,M_GAON,M_DOB,M_WARD,M_CONTACT) values (2,2,'son','mulga','Yes','Male','Maharashtra','Ahmednagar','rahata','wakadi','23/44/90',2,'1234567897');
Insert into SWAP.SMEMBER (MEMBER_ID,FAMILY_ID,M_NAME_E,M_NAME_M,FAMILY_HEAD_STATUS,M_SEX,M_STATE,M_DIST,M_TAL,M_GAON,M_DOB,M_WARD,M_CONTACT) values (1,1,'swapnil','sfsdf','Yes','Male','Maharashtra','Ahmednagar','rahata','babulwadi','10/06/2001',2,'708382041');
REM INSERTING into SWAP.SSMSCONTACTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FAMILY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWAP"."FAMILY_PK" ON "SWAP"."SFAMILY" ("FAMILY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SWAP"."MEMBER_PK" ON "SWAP"."SMEMBER" ("FAMILY_ID", "MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SFAMILY
--------------------------------------------------------

  ALTER TABLE "SWAP"."SFAMILY" ADD CONSTRAINT "FAMILY_PK" PRIMARY KEY ("FAMILY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SWAP"."SFAMILY" MODIFY ("FAMILY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SMEMBER
--------------------------------------------------------

  ALTER TABLE "SWAP"."SMEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("FAMILY_ID", "MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SWAP"."SMEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SWAP"."SMEMBER" MODIFY ("FAMILY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SMEMBER
--------------------------------------------------------

  ALTER TABLE "SWAP"."SMEMBER" ADD CONSTRAINT "MEMBER_FK" FOREIGN KEY ("FAMILY_ID")
	  REFERENCES "SWAP"."SFAMILY" ("FAMILY_ID") ENABLE;
