--------------------------------------------------------
--  File created - Monday-March-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCUSTOMER
--------------------------------------------------------

  CREATE TABLE "SWAP"."SCUSTOMER" 
   (	"CUID" VARCHAR2(20 BYTE), 
	"STRINGUID" VARCHAR2(50 BYTE), 
	"CNAME" VARCHAR2(100 BYTE), 
	"CADDRESS" VARCHAR2(500 BYTE), 
	"CVCODE" VARCHAR2(50 BYTE), 
	"CDEPT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SDUTYTYPE
--------------------------------------------------------

  CREATE TABLE "SWAP"."SDUTYTYPE" 
   (	"DUID" VARCHAR2(50 BYTE), 
	"SUID" VARCHAR2(500 BYTE), 
	"HOURS" VARCHAR2(100 BYTE), 
	"KM" VARCHAR2(100 BYTE), 
	"PKGRATE" VARCHAR2(100 BYTE), 
	"CNAME" VARCHAR2(500 BYTE), 
	"VNAME" VARCHAR2(500 BYTE), 
	"EXKMRATE" VARCHAR2(100 BYTE), 
	"DUTYTYPESTRING" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SVEHICLE
--------------------------------------------------------

  CREATE TABLE "SWAP"."SVEHICLE" 
   (	"VUID" VARCHAR2(20 BYTE), 
	"STRINGUID" VARCHAR2(20 BYTE), 
	"VEHICLENAME" VARCHAR2(20 BYTE), 
	"CUSTOMERNAME" VARCHAR2(20 BYTE), 
	"VEHICLENUMBER" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SLOGIN
--------------------------------------------------------

  CREATE TABLE "SWAP"."SLOGIN" 
   (	"UNAME" VARCHAR2(4000 BYTE), 
	"UPASS" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SWAP.SCUSTOMER
SET DEFINE OFF;
Insert into SWAP.SCUSTOMER (CUID,STRINGUID,CNAME,CADDRESS,CVCODE,CDEPT) values ('1','TAL','TAL','Pune','ABC-123','EnTC');
Insert into SWAP.SCUSTOMER (CUID,STRINGUID,CNAME,CADDRESS,CVCODE,CDEPT) values ('2','Mahindra','Mahindra','Mumbai','SDR-256','Mechanical');
Insert into SWAP.SCUSTOMER (CUID,STRINGUID,CNAME,CADDRESS,CVCODE,CDEPT) values ('3','UIT','UIT','Bhosri','UIT-111','IT');
REM INSERTING into SWAP.SDUTYTYPE
SET DEFINE OFF;
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('1','TATA SAFARI-4 Hrs 40 KM-(T)','4','40','1000.0','TAL','TATA SAFARI','15.0','TATA SAFARI-4 Hrs 40 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('2','TATA SAFARI-8 Hrs 80 KM-(T)','8','80','1800.0','TAL','TATA SAFARI','15.0','TATA SAFARI-8 Hrs 80 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('3','TATA SAFARI-0 Hrs 300 KM-(T)','0','300','4500.0','TAL','TATA SAFARI','15.0','TATA SAFARI-0 Hrs 300 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('4','TATA SAFARI-24 Hrs 370 KM-(T)','24','370','5200.0','TAL','TATA SAFARI','15.0','TATA SAFARI-24 Hrs 370 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('5','TATA ARIA-4 Hrs 40 KM-(T)','4','40','1000.0','TAL','TATA ARIA','15.0','TATA ARIA-4 Hrs 40 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('6','TATA ARIA-8 Hrs 80 KM-(T)','8','80','1800.0','TAL','TATA ARIA','15.0','TATA ARIA-8 Hrs 80 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('7','TATA ARIA-0 Hrs 300 KM-(T)','0','300','4500.0','TAL','TATA ARIA','15.0','TATA ARIA-0 Hrs 300 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('8','TATA ARIA-24 Hrs 370 KM-(T)','24','370','5200.0','TAL','TATA ARIA','15.0','TATA ARIA-24 Hrs 370 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('9','INNOVA-4 Hrs 40 KM-(T)','4','40','1000.0','TAL','INNOVA','15.0','INNOVA-4 Hrs 40 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('10','INNOVA-8 Hrs 80 KM-(T)','8','80','1800.0','TAL','INNOVA','15.0','INNOVA-8 Hrs 80 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('11','INNOVA-0 Hrs 300 KM-(T)','0','300','4500.0','TAL','INNOVA','15.0','INNOVA-0 Hrs 300 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('12','INNOVA-24 Hrs 370 KM-(T)','24','370','5200.0','TAL','INNOVA','15.0','INNOVA-24 Hrs 370 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('13','MONTHLY INDICA-10 Hrs 2000 KM-(T)','10','2000','27500.0','TAL','MONTHLY INDICA','10.0','MONTHLY INDICA-10 Hrs 2000 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('14','TATA INDICA-4 Hrs 40 KM-(T)','4','40','520.0','TAL','TATA INDICA','10.0','TATA INDICA-4 Hrs 40 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('15','TATA INDICA-8 Hrs 80 KM-(T)','8','80','1050.0','TAL','TATA INDICA','10.0','TATA INDICA-8 Hrs 80 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('16','TATA INDIGO-4 Hrs 40 KM-(T)','4','40','700.0','TAL','TATA INDIGO','12.0','TATA INDIGO-4 Hrs 40 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('17','TATA INDIGO-8 Hrs 80 KM-(T)','8','80','1300.0','TAL','TATA INDIGO','11.0','TATA INDIGO-8 Hrs 80 KM-(T)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('18','TATA SAFARI-4 Hrs 40 KM-(M)','4','40','520.0','Mahindra','TATA SAFARI','15.0','TATA SAFARI-4 Hrs 40 KM-(M)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('19','TATA SUMO-1 Hrs 10 KM-(U)','1','10','100.0','UIT','TATA SUMO','5.0','TATA SUMO-1 Hrs 10 KM-(U)');
Insert into SWAP.SDUTYTYPE (DUID,SUID,HOURS,KM,PKGRATE,CNAME,VNAME,EXKMRATE,DUTYTYPESTRING) values ('20','TATA SUMO-45 Hrs 450 KM-(U)','45','450','4500.0','UIT','TATA SUMO','45.0','TATA SUMO-45 Hrs 450 KM-(U)');
REM INSERTING into SWAP.SVEHICLE
SET DEFINE OFF;
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('1','TATA SAFARI','TATA SAFARI','TAL','MH-16 BF 8720');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('2','TATA ARIA','TATA ARIA','TAL','MH-16 BF 8720');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('3','INNOVA','INNOVA','TAL','MH-16 BF 8720');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('4','MONTHLY INDICA','MONTHLY INDICA','TAL','MH-16 BF 8720');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('5','TATA INDICA','TATA INDICA','TAL','MH-16 BF 8720');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('6','TATA INDIGO','TATA INDIGO','TAL','MH-16 BF 8720');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('7','TATA MANZA','TATA MANZA','TAL','MH-16 BF 8720');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('8','TATA SUMO','TATA SUMO','Mahindra','MH-16 BF 0157');
Insert into SWAP.SVEHICLE (VUID,STRINGUID,VEHICLENAME,CUSTOMERNAME,VEHICLENUMBER) values ('9','Shine','Shine','Swap','MH 16 bf 0157');
REM INSERTING into SWAP.SLOGIN
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table SVEHICLE
--------------------------------------------------------

  ALTER TABLE "SWAP"."SVEHICLE" MODIFY ("VUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SLOGIN
--------------------------------------------------------

  ALTER TABLE "SWAP"."SLOGIN" MODIFY ("UNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SWAP"."SLOGIN" MODIFY ("UPASS" NOT NULL ENABLE);
