--
-- File generated with SQLiteStudio v3.1.1 on Mon Mar 27 10:58:47 2017
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: SCUSTOMER
CREATE TABLE SCUSTOMER (
    CUID      VARCHAR2 (20),
    STRINGUID VARCHAR2 (100),
    CNAME     VARCHAR2 (500),
    CADDRESS  VARCHAR2 (1000),
    CVCODE    VARCHAR2 (100),
    CDEPT     VARCHAR2 (100) 
);


-- Table: SDUTYTYPE
CREATE TABLE SDUTYTYPE (
    DUID           VARCHAR2 (100),
    SUID           VARCHAR2 (500),
    HOURS          VARCHAR2 (100),
    KM             VARCHAR2 (100),
    PKGRATE        VARCHAR2 (100),
    CNAME          VARCHAR2 (500),
    VNAME          VARCHAR2 (500),
    EXKMRATE       VARCHAR2 (100),
    DUTYTYPESTRING VARCHAR2 (500) 
);


-- Table: SVEHICLE
CREATE TABLE SVEHICLE (
    VUID          VARCHAR2 (100),
    STRINGUID     VARCHAR2 (500),
    VEHICLENAME   VARCHAR2 (500),
    CUSTOMERNAME  VARCHAR2 (500),
    VEHICLENUMBER VARCHAR2 (200),
    MRATE         VARCHAR2 (100),
    EXKMRATE      VARCHAR2 (100) 
);


COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
